add chinese translation
OpenZeppelin/ethernaut pull request #313
Opened 2022-01-12 01:57 UTC by chrisyang2003

2022-01-12 21:25 UTC, sunrentao requested changes

2022-01-12 21:25 UTC, sunrentao commented on client/src/gamedata/cn_simplified/descriptions/levels/naughtcoin.md
> +NaughtCoin 是一种 ERC20 代币，而且您已经持有所有这些代币。问题是您只能在 10 年之后才能转移它们。您能尝试将它们转移到另一个地址，以便您可以自由转移它们吗？通过将您的代币余额变为 0 来完成此级别。
NaughtCoin 是一种 ERC20 代币，而且您已经持有这些代币。问题是您只能在 10 年之后才能转移它们。您能尝试将它们转移到另一个地址，以便您可以自由使用它们吗？通过将您的代币余额变为 0 来完成此关卡。

2022-01-12 21:25 UTC, sunrentao commented on client/src/gamedata/cn_simplified/descriptions/levels/naughtcoin_complete.md
> +当您使用自己的代码以外的代码时，最好熟悉它以充分了解它们是如何编写在一起的。当有多个进口级别（您的进口有进口）或您正在实施授权控制时，这一点尤其重要。在此示例中，当您允许或阻止人们做某事时，开发人员可能会查看代码并认为传输是移动Token的唯一方法，但发现还有其他方法时可以使用不同的实现来执行相同的操作。
当您使用自己的代码以外的代码时，最好熟悉它以充分了解它们是如何编写在一起的。当有多个层级的导入时（您的导入包含其它导入）或您正在实施授权控制时，这一点尤其重要, 比如当您允许或阻止人们做某事时. 在这个案例中, 开发人员可能会查看代码并认为 `transfer` 函数是移动Token的唯一方法，但发现还有其他方法可以使用不同的实现来执行相同的操作。

2022-01-19 20:07 UTC, frangio commented
Does this conflict with #314 ?

2022-01-20 19:57 UTC, sunrentao commented
Hi, maybe modify the translation regarding to my suggestion?

2022-01-31 07:34 UTC, xaler5 commented
@frangio I don't see any conflict with other pull request. Merging this. I provided feedback in the other PR

2022-01-31 07:34 UTC, xaler5 approved these changes

2022-01-31 07:38 UTC, merged