Arabic translation continued from PR#321
OpenZeppelin/ethernaut pull request #521
Opened 2022-12-30 21:59 UTC by OjusWiZard

2023-01-02 17:47 UTC, EmanHerawy commented on client/src/gamedata/ar/strings.json
> +  "getNewInstance": "احصل على تكليف جديد",
Why you are translating " instance into " تكاليف" ؟

2023-01-02 17:50 UTC, EmanHerawy commented on client/src/gamedata/ar/strings.json
> +  "instance": "التكليف",
what about:
نموذج  وهى الاقرب للمعنى ، او " نسخه" وهى اﻻقرب للواقع ، ﻻنى فعليا باخد نسخه خاصه بيا من الاوبجيكت

2023-01-02 17:51 UTC, EmanHerawy commented on client/src/gamedata/ar/strings.json
> +  "ethernautNotFoundMessage": "عقد الايثناوت الحالي مش موجود في الشبكة. اتأكد انه (1) انك بتستعمل ميتاماسك, (2) الميتاماسك مشبوكة على شبة الرينكنبي للفحص, (3) انها متصلة, (4 اختياري) ابتدائا من نوفمب
ده ميكس بين العامية المصريه واللغه العربيه ، اظن لو وحدناه وبقى يا عاميه ، يا فصحى هيكون افضل

2023-01-02 17:53 UTC, EmanHerawy commented on client/src/gamedata/ar/strings.json
> +  "noPlayerAddressMessage": "لم يتم اكتشاف عنوان لاعب!تأكد من أن 1) قمت بتثبيت امتداد متصفح Metamask و 2) الذي تم فتحه.3 اختياري) من 2 نوفمبر ، يمكنك تشغيل وضع الخصوصية (إيقاف افتراضيًا) في الإعدادات
no consistency
لو هنكتب ميتامسك بالعربي .. المفروض تكون فى كل البروجيكت  ، سطر 77 مكتوب بالعربي

2023-01-02 18:01 UTC, EmanHerawy commented on client/src/gamedata/ar/strings.json
> +  "noPlayerAddressMessage": "لم يتم اكتشاف عنوان لاعب!تأكد من أن 1) قمت بتثبيت امتداد متصفح Metamask و 2) الذي تم فتحه.3 اختياري) من 2 نوفمبر ، يمكنك تشغيل وضع الخصوصية (إيقاف افتراضيًا) في الإعدادات
اظن " الكشف عن معلوماتك" هيكون تعبير اكثر لباقة بدلا من " فضح معلوماتك" ﻻن اللفظ ذاته سلبي وبيعنى اضمار سوء النية فى استغلال البيانات دى

2023-01-02 18:08 UTC, EmanHerawy requested changes
Good job  but the current version miss consistency in multiple places 

1.  tow translations for the same term  
2. mix between Fusha and slang
3.  using English terms and Arabic terms in other places

2023-01-02 19:08 UTC, xaler5 commented
Hey @EmanHerawy we are trying our best since we are not arabic and these translations come from external sources. Would you like to contribute and improve them ?

2023-01-03 09:20 UTC, xaler5 commented
Adding @core17tk to the loop as he initiated the initial translation

2023-01-03 15:54 UTC, xaler5 commented
@EmanHerawy let's do the following then, I'll merge this so you can open your own PR with the changes you think are best for Ethernaut. Wdyt ?

2023-01-03 15:56 UTC, EmanHerawy commented
Sounds good 💪

2023-01-03 16:18 UTC, merged